name: 'openapi to json schema action'
description: 'Retrieve openapi specification file and return json schema file'
branding:
  icon: 'box'
  color: 'purple'
inputs:
  specification-url:
    description: 'Specification URL'
    required: true
    # default: ''
outputs:
  time:
    description: 'The time we processed the request'
    value: ${{ steps.time-id.outputs.time-id }}
  specificationURL:
    description: 'The specification URL that was entered'
    value: ${{ steps.specification-id.outputs.specification-id }}
runs:
  using: 'composite'
  steps:
    - id: time-id
      run: |
        echo "::set-output name=time-id::$(date)"
      shell: bash
    - id: specification-id
      run: |
        echo "::set-output name=specification-id::${{ inputs.specification-url }}"
      shell: bash
    - shell: 'bash'
      run: |
        docker run -u 1001 --rm --workdir /github/workspace -v "$GITHUB_WORKSPACE":"/github/workspace" \
          openapitools/openapi-generator-cli generate \
          -i ${{ inputs.specification-url }} \
          -g openapi \
          -o /github/workspace/openapi
